### ISSUE TITLE
Tablet mode - the alignment seems to be odd. 

### ISSUE THREAD

**Issue by sillysachin** [opticod/PopularMovies#1]
Is this the same view as in smaller handsets. The screen usage for navigation can be improved for Tablet . A readme on setup would also help to get started on the app debuggin.

![screenshot 08_01am jan 08 2017](https://cloud.githubusercontent.com/assets/333723/21746877/834b0e0e-d57a-11e6-8b60-7e20c8d47695.png)

**Comment by opticod** [comment]
@sillysachin, in phone layout it has only one column, in 7" tablet it has two layout, one for the movie list and other one for movie details. In more bigger screen, the movie list column can be further divided into multiple column depending upon screen size. Once the data is loaded, the detail column is well filled with data.

It looks that you haven't provided the API key and the data is not being loaded. If that is the case, please see [README#development-setup](https://github.com/opticod/Opti-Movies#development-setup) . You can get your API key here : https://www.themoviedb.org/documentation/api

**Comment by opticod** [comment]
Let me know, if there is any more issues. Thank you. Closing it for now.
